module spdataio
    implicit none
    integer lsp, lst
    integer iosp
    real(kind=8) psiw, ped
    real(kind=8), allocatable,dimension(:,:,:) :: bsp, xsp, zsp, gsp, rd,fsp,delsp
    real(kind=8), allocatable, dimension(:,:) :: qpsi, gpsi, ppsi, rpsi, torpsi
    character(len=99) fname
    character*10 datetime(3)
    integer date_time(8)
contains

subroutine filename(name)
    implicit none
    character(*) name
    fname = trim(name)
end subroutine filename

subroutine allocate(lsp_in, lst_in)
    implicit none
    integer, intent(in) :: lsp_in, lst_in
!f2py intent(in) lsp_in, lst_in
    lsp = lsp_in
    lst = lst_in
    allocate(bsp(9,lsp,lst), xsp(9,lsp,lst), zsp(9,lsp,lst),gsp(9,lsp,lst),rd(9,lsp,lst),&
    qpsi(3,lsp),gpsi(3,lsp),ppsi(3,lsp),rpsi(3,lsp),torpsi(3,lsp),fsp(9,lsp,lst),delsp(9,lsp,lst))
end subroutine

subroutine deallocate
    deallocate(bsp, xsp, zsp,gsp,rd,qpsi,gpsi,ppsi,rpsi,torpsi,fsp,delsp)
end subroutine

subroutine write
    implicit none
    integer i
    iosp = 687
    call date_and_time(datetime(1), datetime(2), datetime(3), date_time)
    open(iosp,file=fname, status="replace")
    write(iosp,*) datetime(1), "Generated by XMAP. Author: weixishuo@gmail.com"
    write(iosp,102) lsp, lst-1, 0, 0
    write(iosp,101) psiw, ped
    do i=1,lsp
        write(iosp,*) "ipsi=",i
        write(iosp,101)bsp(1,i,:) !B-field
        write(iosp,101)bsp(2,i,:)
        write(iosp,101)bsp(3,i,:)
        write(iosp,101)bsp(4,i,:)
        write(iosp,101)bsp(5,i,:)
        write(iosp,101)bsp(6,i,:)
        write(iosp,101)bsp(7,i,:)
        write(iosp,101)bsp(8,i,:)
        write(iosp,101)bsp(9,i,:)
        write(iosp,101)xsp(1,i,:) !X-coordinate
        write(iosp,101)xsp(2,i,:)
        write(iosp,101)xsp(3,i,:)
        write(iosp,101)xsp(4,i,:)
        write(iosp,101)xsp(5,i,:)
        write(iosp,101)xsp(6,i,:)
        write(iosp,101)xsp(7,i,:)
        write(iosp,101)xsp(8,i,:)
        write(iosp,101)xsp(9,i,:)
        write(iosp,101)zsp(1,i,:) !Z-coordinate
        write(iosp,101)zsp(2,i,:)
        write(iosp,101)zsp(3,i,:)
        write(iosp,101)zsp(4,i,:)
        write(iosp,101)zsp(5,i,:)
        write(iosp,101)zsp(6,i,:)
        write(iosp,101)zsp(7,i,:)
        write(iosp,101)zsp(8,i,:)
        write(iosp,101)zsp(9,i,:)
        write(iosp,101)gsp(1,i,:) !Gicobian
        write(iosp,101)gsp(2,i,:)
        write(iosp,101)gsp(3,i,:)
        write(iosp,101)gsp(4,i,:)
        write(iosp,101)gsp(5,i,:)
        write(iosp,101)gsp(6,i,:)
        write(iosp,101)gsp(7,i,:)
        write(iosp,101)gsp(8,i,:)
        write(iosp,101)gsp(9,i,:)
        write(iosp,101)qpsi(:,i) !q
        write(iosp,101)gpsi(:,i) !g-current
        write(iosp,101)rd(1:3,i,1) !i-current
        write(iosp,101)ppsi(:,i) !pressure
        write(iosp,101)rpsi(:,i) !minor radius
        write(iosp,101)torpsi(:,i) !toroidal flux
    enddo
    write(iosp,102) 0,0
    write(iosp,101) 0.0,0.0,0.0
    write(iosp,101) 0.0,0.0
   do i=1,lsp
       write(iosp,101)fsp(1,i,:) !Nu
       write(iosp,101)fsp(2,i,:)
       write(iosp,101)fsp(3,i,:)
       write(iosp,101)fsp(4,i,:)
       write(iosp,101)fsp(5,i,:)
       write(iosp,101)fsp(6,i,:)
       write(iosp,101)fsp(7,i,:)
       write(iosp,101)fsp(8,i,:)
       write(iosp,101)fsp(9,i,:)
    enddo
    do i=1,lsp
       write(iosp,101)delsp(1,i,:) !delta-current
       write(iosp,101)delsp(2,i,:)
       write(iosp,101)delsp(3,i,:)
       write(iosp,101)delsp(4,i,:)
       write(iosp,101)delsp(5,i,:)
       write(iosp,101)delsp(6,i,:)
       write(iosp,101)delsp(7,i,:)
       write(iosp,101)delsp(8,i,:)
       write(iosp,101)delsp(9,i,:)
    enddo
    close(iosp)

101 format(1p4e18.10)
102 format(6i4)
103 format(5e16.9)
end subroutine write

end module spdataio
